server:
  port: 8080
  tomcat:
     uri-encoding: UTF-8
     max-threads: 1000
     min-spare-threads: 30
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
        ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
            connection-test-query: SELECT 1
            ## 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 30000
            ## 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            ## 连接池最大连接数，默认是10
            maximum-pool-size: 10
            ## 最小空闲连接数量
            minimum-idle: 5
            ## 连接池名字
            pool-name: MyHikariCP
        password: root
        url: jdbc:mysql://39.107.235.218:3306/system_admin?serverTimezone=UTC
        username: root
        #-----更多配置可访问：https://github.com/brettwooldridge/HikariCP
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
    #    hibernate:
     #       ddl-auto: update
      #  show-sql: true
logging:
  config: classpath:logback.xml
  path: /usr/local/logs
#自定义属性
custom:
   imageResourceHandler: /image/**
    #文件上传目录
   imageResourceLocations: /mnt/images/
   #系统配置文件key前缀
   configKey: dev_sys_config_
redis:
   host: 39.107.235.218
   password: 515227
   poolMaxIdle: 10
   poolMaxTotal: 10
   poolMaxWait: 3
   port: 6379
   timeout: 3